import { FurnitureLibraryItem } from '../types/ar-view';

export const FURNITURE_LIBRARY: FurnitureLibraryItem[] = [
    // Seating
    {
        id: 'sofa-two-seater-scandinavian',
        name: 'Scandinavian Two-Seater Sofa',
        emoji: '🛋️',
        price: '$1,499',
        color: '#E5E7EB',
        category: 'seating',
        dimensions: { width: 1.5, length: 0.85, height: 0.85 },
        description: 'Minimalist two-seater sofa with curved backrest, thin tapered wooden legs, and neutral fabric upholstery.',
        material: 'fabric',
        styles: ['Modern', 'Minimalist', 'Scandinavian', 'Mid-Century'],
        roomTypes: ['Living Room', 'Lounge'],
    },
    {
        id: 'sofa-modern',
        name: 'Modern Sofa',
        emoji: '🛋️',
        price: '$1,299',
        color: '#2563EB',
        category: 'seating',
        dimensions: { width: 2.1, length: 0.95, height: 0.85 },
    },
    {
        id: 'accent-chair',
        name: 'Accent Chair',
        emoji: '🪑',
        price: '$449',
        color: '#DB2777',
        category: 'seating',
        dimensions: { width: 0.8, length: 0.8, height: 0.95 },
    },
    {
        id: 'dining-chair',
        name: 'Dining Chair',
        emoji: '🪑',
        price: '$199',
        color: '#8B5CF6',
        category: 'seating',
        dimensions: { width: 0.5, length: 0.5, height: 0.9 },
    },
    // Tables
    {
        id: 'coffee-table',
        name: 'Coffee Table',
        emoji: '🪑',
        price: '$399',
        color: '#14B8A6',
        category: 'tables',
        dimensions: { width: 1.0, length: 0.6, height: 0.42 },
    },
    {
        id: 'dining-table',
        name: 'Dining Table',
        emoji: '🪑',
        price: '$899',
        color: '#F59E0B',
        category: 'tables',
        dimensions: { width: 1.5, length: 0.9, height: 0.75 },
    },
    {
        id: 'side-table',
        name: 'Side Table',
        emoji: '🪑',
        price: '$249',
        color: '#EC4899',
        category: 'tables',
        dimensions: { width: 0.5, length: 0.5, height: 0.6 },
    },
    // Storage
    {
        id: 'bookshelf',
        name: 'Bookshelf',
        emoji: '📚',
        price: '$599',
        color: '#7C3AED',
        category: 'storage',
        dimensions: { width: 1.0, length: 0.4, height: 2.1 },
    },
    {
        id: 'tv-stand',
        name: 'TV Stand',
        emoji: '📺',
        price: '$549',
        color: '#6366F1',
        category: 'storage',
        dimensions: { width: 1.8, length: 0.5, height: 0.6 },
    },
    {
        id: 'wardrobe',
        name: 'Wardrobe',
        emoji: '🚪',
        price: '$1,199',
        color: '#475569',
        category: 'storage',
        dimensions: { width: 1.2, length: 0.6, height: 2.0 },
    },
    // Lighting
    {
        id: 'floor-lamp',
        name: 'Floor Lamp',
        emoji: '💡',
        price: '$149',
        color: '#F97316',
        category: 'lighting',
        dimensions: { width: 0.3, length: 0.3, height: 1.8 },
    },
    {
        id: 'table-lamp',
        name: 'Table Lamp',
        emoji: '💡',
        price: '$89',
        color: '#FBBF24',
        category: 'lighting',
        dimensions: { width: 0.25, length: 0.25, height: 0.6 },
    },
    // Decor
    {
        id: 'planter',
        name: 'Tall Planter',
        emoji: '🌿',
        price: '$129',
        color: '#10B981',
        category: 'decor',
        dimensions: { width: 0.4, length: 0.4, height: 0.8 },
    },
    {
        id: 'mirror',
        name: 'Standing Mirror',
        emoji: '🪞',
        price: '$299',
        color: '#94A3B8',
        category: 'decor',
        dimensions: { width: 0.6, length: 0.05, height: 1.8 },
    },
    {
        id: 'art-piece',
        name: 'Abstract Wall Art',
        emoji: '🖼️',
        price: '$349',
        color: '#F43F5E',
        category: 'decor',
        dimensions: { width: 0.8, length: 0.02, height: 1.0 },
    },
    // Bedroom
    {
        id: 'bed-king',
        name: 'King Size Bed',
        emoji: '🛏️',
        price: '$2,499',
        color: '#1E293B',
        category: 'bedroom',
        dimensions: { width: 2.0, length: 2.1, height: 1.2 },
    },
    {
        id: 'nightstand',
        name: 'Minimalist Nightstand',
        emoji: '🪑',
        price: '$199',
        color: '#F1F5F9',
        category: 'bedroom',
        dimensions: { width: 0.45, length: 0.4, height: 0.5 },
    },
];
