import { StyleSheet } from 'react-native';
import { getHorizontalPadding } from '@/utils/responsive';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  scrollView: {
    flex: 1,
  },
  content: {
    padding: 16,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: getHorizontalPadding(16),
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: '#1E293B',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  backButton: {
    fontSize: 16,
    color: '#6B4CE6',
    fontWeight: '600',
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  placeholder: {
    width: 40,
  },
  helpButton: {
    fontSize: 20,
  },
  headerButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#334155',
  },
  headerButtonText: {
    fontSize: 18,
  },
  comparisonButtonActive: {
    backgroundColor: '#34C759',
  },
  offlineBanner: {
    backgroundColor: '#FF9500',
    padding: 8,
    alignItems: 'center',
  },
  offlineText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  loadingSubtext: {
    marginTop: 8,
    fontSize: 14,
    color: '#94A3B8',
  },
  progressContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 16,
    backgroundColor: '#1E293B',
  },
  progressDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#334155',
  },
  progressDotActive: {
    backgroundColor: '#6B4CE6',
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  progressDotCompleted: {
    backgroundColor: '#10B981',
  },
  stepContainer: {
    alignItems: 'center',
  },
  stepTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
  },
  stepSubtitle: {
    fontSize: 16,
    color: '#94A3B8',
    marginBottom: 24,
    textAlign: 'center',
  },
  optionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 12,
  },
  backStepButton: {
    marginTop: 24,
    padding: 12,
  },
  backStepButtonText: {
    fontSize: 16,
    color: '#6B4CE6',
    fontWeight: '600',
  },
  welcomeContainer: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  welcomeEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  welcomeTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontSize: 16,
    color: '#94A3B8',
    textAlign: 'center',
    marginBottom: 32,
    paddingHorizontal: getHorizontalPadding(20),
    lineHeight: 24,
  },
  startButton: {
    backgroundColor: '#6B4CE6',
    paddingVertical: 16,
    paddingHorizontal: getHorizontalPadding(48),
    borderRadius: 12,
  },
  startButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  breadcrumbContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#1E293B',
    gap: 8,
  },
  breadcrumbItem: {
    padding: 4,
  },
  breadcrumbText: {
    fontSize: 14,
    color: '#6B4CE6',
    fontWeight: '600',
  },
  breadcrumbSeparator: {
    fontSize: 14,
    color: '#64748B',
  },
  breadcrumbActive: {
    color: '#FFFFFF',
  },
  errorBanner: {
    backgroundColor: '#FF3B30',
    padding: 12,
    marginHorizontal: 16,
    marginTop: 8,
    borderRadius: 8,
  },
  infoBanner: {
    backgroundColor: '#FF9500',
  },
  errorText: {
    color: '#FFFFFF',
    fontSize: 14,
    textAlign: 'center',
  },
  userChoicesCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
  },
  userChoicesTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#94A3B8',
    marginBottom: 12,
    textAlign: 'center',
  },
  userChoicesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  userChoiceBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(107, 76, 230, 0.15)',
    paddingVertical: 6,
    paddingHorizontal: getHorizontalPadding(12),
    borderRadius: 16,
    gap: 4,
  },
  userChoiceEmoji: {
    fontSize: 16,
  },
  userChoiceText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  userChoiceArrow: {
    fontSize: 14,
    color: '#64748B',
  },
  statsDashboard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
  },
  statsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 12,
  },
  statCard: {
    alignItems: 'center',
  },
  statIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '700',
    color: '#6B4CE6',
  },
  statLabel: {
    fontSize: 12,
    color: '#94A3B8',
  },
  statsInfo: {
    fontSize: 12,
    color: '#94A3B8',
    textAlign: 'center',
  },
  topThemeCard: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: '#6B4CE6',
  },
  bestBadge: {
    position: 'absolute',
    top: -12,
    left: 16,
    backgroundColor: '#FFD700',
    paddingVertical: 4,
    paddingHorizontal: getHorizontalPadding(12),
    borderRadius: 12,
  },
  bestBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#0F172A',
  },
  topThemeTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginTop: 8,
    marginBottom: 8,
  },
  topThemeDescription: {
    fontSize: 14,
    color: '#94A3B8',
    lineHeight: 20,
    marginBottom: 16,
  },
  confidenceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(107, 76, 230, 0.15)',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  confidenceLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  confidenceValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#6B4CE6',
  },
  colorPaletteSection: {
    marginBottom: 16,
  },
  sectionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  colorPalette: {
    flexDirection: 'row',
    gap: 8,
  },
  colorSwatch: {
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  materialSection: {
    marginBottom: 16,
  },
  materialText: {
    fontSize: 14,
    color: '#94A3B8',
  },
  decorSection: {
    marginBottom: 16,
  },
  decorText: {
    fontSize: 14,
    color: '#94A3B8',
  },
  generatedImageContainer: {
    marginBottom: 16,
    borderRadius: 12,
    overflow: 'hidden',
  },
  generatedImage: {
    width: '100%',
    height: 200,
  },
  themeActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  likeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#334155',
    justifyContent: 'center',
    alignItems: 'center',
  },
  likeButtonActive: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
  },
  likeButtonText: {
    fontSize: 20,
  },
  generateImageButton: {
    flex: 1,
    backgroundColor: '#334155',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  generateImageButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  applyButton: {
    flex: 1,
    backgroundColor: '#6B4CE6',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  applyButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  alternativesSection: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  historySection: {
    marginBottom: 24,
  },
  historyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  historyFilterButton: {
    backgroundColor: '#6B4CE6',
    paddingHorizontal: getHorizontalPadding(12),
    paddingVertical: 6,
    borderRadius: 8,
  },
  historyFilterButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  historyFilters: {
    marginBottom: 12,
  },
  historySearchInput: {
    backgroundColor: '#1E293B',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#334155',
    color: '#FFFFFF',
  },
  historySortRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  historySortLabel: {
    fontSize: 12,
    color: '#94A3B8',
  },
  historySortChip: {
    backgroundColor: '#334155',
    paddingHorizontal: getHorizontalPadding(10),
    paddingVertical: 6,
    borderRadius: 12,
  },
  historySortChipActive: {
    backgroundColor: '#6B4CE6',
  },
  historySortChipText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  historyCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 12,
    marginRight: 12,
    width: 160,
    borderWidth: 1,
    borderColor: '#334155',
  },
  historyCardLiked: {
    borderColor: '#FF3B30',
    borderWidth: 2,
  },
  historyCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  historyCardConfidence: {
    fontSize: 12,
    color: '#6B4CE6',
    fontWeight: '600',
    marginBottom: 8,
  },
  historyCardColors: {
    flexDirection: 'row',
    gap: 4,
  },
  historyColorDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  historyLikedBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    fontSize: 14,
  },
  resultActions: {
    flexDirection: 'row',
    gap: 12,
  },
  retakeButton: {
    flex: 1,
    backgroundColor: '#334155',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  retakeButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  collectionsButton: {
    flex: 1,
    backgroundColor: '#6B4CE6',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  collectionsButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: getHorizontalPadding(16),
    paddingTop: 60,
    paddingBottom: 16,
    backgroundColor: '#1E293B',
    borderBottomWidth: 1,
    borderBottomColor: '#334155',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  modalClose: {
    fontSize: 24,
    color: '#94A3B8',
  },
  modalContent: {
    flex: 1,
    padding: 16,
  },
  collectionCard: {
    backgroundColor: '#1E293B',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#334155',
  },
  collectionName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  collectionCount: {
    fontSize: 14,
    color: '#94A3B8',
    marginBottom: 12,
  },
  collectionActions: {
    flexDirection: 'row',
    gap: 16,
  },
  collectionActionText: {
    fontSize: 14,
    color: '#6B4CE6',
    fontWeight: '600',
  },
  deleteText: {
    color: '#EF4444',
  },
  createCollectionButton: {
    backgroundColor: '#6B4CE6',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 8,
  },
  createCollectionButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  createModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  createModalContent: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 24,
    width: '85%',
    maxWidth: 400,
  },
  createModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 16,
    textAlign: 'center',
  },
  createModalInput: {
    backgroundColor: '#0F172A',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#334155',
    color: '#FFFFFF',
  },
  createModalInputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  createModalActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  createModalCancel: {
    flex: 1,
    backgroundColor: '#334155',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  createModalCancelText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  createModalConfirm: {
    flex: 1,
    backgroundColor: '#6B4CE6',
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  createModalConfirmText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  tutorialOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  tutorialModal: {
    backgroundColor: '#1E293B',
    borderRadius: 20,
    padding: 24,
    width: '85%',
    maxWidth: 400,
  },
  tutorialHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  tutorialTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    flex: 1,
  },
  tutorialCloseText: {
    fontSize: 24,
    color: '#EF4444',
  },
  tutorialDescription: {
    fontSize: 15,
    color: '#94A3B8',
    lineHeight: 22,
    marginBottom: 20,
  },
  tutorialProgress: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 20,
  },
  tutorialDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#334155',
  },
  tutorialDotActive: {
    backgroundColor: '#6B4CE6',
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  tutorialButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  tutorialNavButton: {
    flex: 1,
    backgroundColor: '#334155',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  tutorialNavButtonPrimary: {
    backgroundColor: '#6B4CE6',
  },
  tutorialNavText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  customDesignSection: {
    backgroundColor: '#1E293B',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
  },
  customDesignSubtitle: {
    fontSize: 14,
    color: '#94A3B8',
    marginBottom: 16,
    textAlign: 'center',
  },
  customDesignInput: {
    backgroundColor: '#0F172A',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#334155',
    color: '#FFFFFF',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  generateCustomImageButton: {
    backgroundColor: '#6B4CE6',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  generateCustomImageButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  customImageContainer: {
    marginTop: 16,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  customGeneratedImage: {
    width: '100%',
    height: 300,
  },
  removeCustomImageButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeCustomImageButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  attributionContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 8,
    paddingHorizontal: getHorizontalPadding(12),
  },
  attributionText: {
    color: '#FFFFFF',
    fontSize: 11,
    textAlign: 'center',
  },
});
