import { StyleSheet, Dimensions } from 'react-native';
import { colors, radii } from '@/components/ui/theme';

const screenHeight = Dimensions.get('window').height;
const maxPanelHeight = screenHeight * 0.5; // 50% of screen height

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#05070a',
  },
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 32,
    backgroundColor: '#05070a',
  },
  permissionIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
  },
  permissionEmoji: {
    fontSize: 72,
    marginBottom: 20,
  },
  permissionTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 12,
  },
  permissionText: {
    fontSize: 15,
    textAlign: 'center',
    color: '#94a3b8',
    marginBottom: 24,
  },
  permissionButton: {
    backgroundColor: '#2563eb',
    borderRadius: 12,
    paddingVertical: 16,
    paddingHorizontal: 32,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  permissionButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  cameraWrapper: {
    flex: 1,
    position: 'relative',
  },
  glContainer: {
    flex: 1,
  },
  placeholderView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  placeholderIconContainer: {
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  placeholderTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 10,
  },
  placeholderText: {
    fontSize: 15,
    color: '#94a3b8',
    textAlign: 'center',
    lineHeight: 22,
  },
  topControls: {
    position: 'absolute',
    top: 58,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    zIndex: 10,
  },
  backButton: {
    backgroundColor: '#FFFFFF',
    minWidth: 80,
    height: 44,
    borderRadius: 22,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  backButtonText: {
    color: '#6B4CE6',
    fontSize: 16,
    fontWeight: '600',
  },
  statsBadgeGroup: {
    flexDirection: 'row',
    gap: 12,
  },
  statPill: {
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    alignItems: 'flex-start',
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  statLabel: {
    color: '#94a3b8',
    fontSize: 11,
    marginBottom: 4,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statValue: {
    color: '#ffffff',
    fontWeight: '800',
    fontSize: 16,
    letterSpacing: 0.2,
  },
  anchorStatusBadge: {
    position: 'absolute',
    top: 120,
    left: 20,
    right: 20,
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 0,
    zIndex: 9,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  anchorStatusGood: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  anchorStatusMedium: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  anchorStatusPoor: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  anchorStatusTitle: {
    color: '#4C1D95',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  anchorStatusSubtitle: {
    color: '#7C3AED',
    fontSize: 13,
    fontWeight: '500',
  },
  // Subtle styles for when furniture is placed
  anchorStatusSubtle: {
    opacity: 0.6,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
  },
  anchorStatusCorner: {
    top: 80,
    // Position from right edge - set left to a large value to override base left:20
    // This allows right:20 to position from right while maxWidth limits size
    left: 1000, // Large value to effectively position from right
    right: 20,
    minWidth: 140,
    maxWidth: 200,
  },
  anchorStatusTitleSmall: {
    fontSize: 13,
    marginBottom: 2,
  },
  anchorStatusSubtitleSmall: {
    fontSize: 11,
  },
  // Corner status indicator (subtle dot)
  cornerStatusIndicator: {
    position: 'absolute',
    top: 80,
    right: 20,
    width: 12,
    height: 12,
    zIndex: 9,
  },
  cornerStatusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  cornerStatusDotGood: {
    backgroundColor: '#10B981', // Green
  },
  cornerStatusDotMedium: {
    backgroundColor: '#F59E0B', // Amber
  },
  cornerStatusDotPoor: {
    backgroundColor: '#EF4444', // Red
  },
  placementHint: {
    position: 'absolute',
    bottom: 150,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
  },
  hintContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  hintEmoji: {
    fontSize: 32,
  },
  hintTextContainer: {
    flex: 1,
    gap: 2,
  },
  hintTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  hintDescription: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
  },
  collisionWarning: {
    color: '#fbbf24',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
  },
  safetyWarning: {
    color: '#fbbf24',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 6,
  },
  safetyInfo: {
    color: '#60a5fa',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 6,
  },
  dragIndicator: {
    position: 'absolute',
    top: 180,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  dragIndicatorSubtle: {
    opacity: 0.9,
    backgroundColor: 'rgba(255, 165, 0, 0.95)', // Light orange background like in the image
    top: 100, // Move higher to avoid blocking furniture
    padding: 12,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  dragIndicatorIcon: {
    fontSize: 32,
  },
  dragIndicatorText: {
    flex: 1,
    color: '#FFFFFF', // White text on orange background
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  dragIndicatorTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  dragIndicatorDescription: {
    color: '#e2e8f0',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 8,
  },
  dragControls: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 8,
    flexWrap: 'wrap',
  },
  dragControlButton: {
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(148, 163, 184, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  dragControlButtonActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.4)',
    borderColor: 'rgba(96, 165, 250, 0.8)',
    shadowColor: '#3b82f6',
    shadowOpacity: 0.3,
  },
  dragControlButtonText: {
    color: '#e2e8f0',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  interactionHint: {
    position: 'absolute',
    bottom: 120,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
  },
  interactionHintText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '500',
  },
  safetyIndicator: {
    position: 'absolute',
    top: 180,
    left: 20,
    right: 20,
    borderRadius: 20,
    padding: 20,
    borderWidth: 2.5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 12,
    maxHeight: 300,
  },
  safetyIndicatorSafe: {
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    borderColor: 'rgba(34, 197, 94, 0.8)',
  },
  safetyIndicatorWarning: {
    backgroundColor: 'rgba(250, 204, 21, 0.15)',
    borderColor: 'rgba(250, 204, 21, 0.8)',
  },
  safetyIndicatorUnsafe: {
    backgroundColor: 'rgba(239, 68, 68, 0.15)',
    borderColor: 'rgba(239, 68, 68, 0.8)',
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  safetyIndicatorContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  safetyIndicatorIcon: {
    fontSize: 32,
  },
  safetyIndicatorText: {
    flex: 1,
    gap: 6,
  },
  safetyIndicatorHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  safetyIndicatorTitle: {
    fontSize: 17,
    fontWeight: '700',
    flex: 1,
    color: '#4C1D95',
  },
  safetyIndicatorTitleSafe: {
    color: '#22c55e',
  },
  safetyIndicatorTitleWarning: {
    color: '#facc15',
  },
  safetyIndicatorTitleUnsafe: {
    color: '#EF4444',
  },
  safetyScoreBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    minWidth: 50,
    alignItems: 'center',
  },
  safetyScoreBadgeSafe: {
    backgroundColor: 'rgba(34, 197, 94, 0.3)',
  },
  safetyScoreBadgeWarning: {
    backgroundColor: 'rgba(250, 204, 21, 0.3)',
  },
  safetyScoreBadgeDanger: {
    backgroundColor: 'rgba(239, 68, 68, 0.3)',
  },
  safetyScoreText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  safetyIndicatorReason: {
    color: '#e2e8f0',
    fontSize: 13,
    fontWeight: '500',
    marginTop: 2,
    lineHeight: 18,
  },
  safetyMetrics: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 4,
  },
  safetyMetric: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '500',
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  recommendationsContainer: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148, 163, 184, 0.2)',
  },
  recommendationsTitle: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 4,
  },
  recommendationText: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '400',
    lineHeight: 16,
    marginTop: 2,
  },
  historyControls: {
    position: 'absolute',
    bottom: 200,
    left: 20,
    flexDirection: 'row',
    gap: 8,
    zIndex: 12,
  },
  historyButton: {
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.5)',
  },
  historyButtonDisabled: {
    opacity: 0.4,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  historyButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
  },
  placedBadge: {
    position: 'absolute',
    top: 130,
    left: 20,
    backgroundColor: 'rgba(37, 99, 235, 0.9)',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 16,
    zIndex: 8,
  },
  placedBadgeText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 13,
  },
  bottomPanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#F5F3FF',
    paddingTop: 24,
    paddingBottom: 34,
    paddingHorizontal: 24,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    borderWidth: 0,
    maxHeight: '50%',
    minHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 8,
    zIndex: 100,
  },
  panelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingHorizontal: 4,
  },
  panelHeaderButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  panelTitle: {
    color: '#4C1D95',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  toggleButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleActive: {
    backgroundColor: '#FFFFFF',
  },
  toggleInactive: {
    backgroundColor: '#6B4CE6',
  },
  markerButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#E2E8F0',
  },
  markerButtonActive: {
    backgroundColor: '#DCFCE7',
  },
  markerButtonDisabled: {
    opacity: 0.5,
  },
  markerButtonText: {
    color: '#0F172A',
    fontSize: 13,
    fontWeight: '700',
  },
  toggleButtonText: {
    color: '#6B4CE6',
    fontWeight: '700',
    fontSize: 15,
    letterSpacing: 0.3,
  },
  toggleButtonTextInactive: {
    color: '#FFFFFF',
  },
  libraryScroll: {
    gap: 12,
    paddingBottom: 12,
    paddingRight: 20,
    paddingLeft: 4,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  anchorHintCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 12,
    borderWidth: 0,
    padding: 14,
    marginBottom: 20,
  },
  anchorHintHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  anchorHintList: {
    gap: 8,
  },
  anchorHintTitle: {
    color: '#e2e8f0',
    fontSize: 14,
    fontWeight: '700',
  },
  anchorHintButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#1d4ed8',
  },
  anchorHintButtonDisabled: {
    backgroundColor: '#1f2937',
    borderWidth: 1,
    borderColor: '#334155',
  },
  anchorHintButtonText: {
    color: '#e2e8f0',
    fontWeight: '600',
    fontSize: 12,
  },
  anchorHintButtonTextDisabled: {
    color: '#64748b',
  },
  anchorHintRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginBottom: 2,
  },
  anchorHintBullet: {
    color: '#3b82f6',
    fontSize: 12,
    marginTop: 2,
  },
  anchorHintText: {
    flex: 1,
    color: '#7C3AED',
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  furnitureCard: {
    width: 150,
    minWidth: 150,
    maxWidth: 150,
    height: 200,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E9E4FF',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
    flexShrink: 0,
  },
  furnitureCardSelected: {
    borderColor: '#6B4CE6',
    backgroundColor: '#F5F3FF',
    borderWidth: 2,
  },
  furnitureEmojiWrapper: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: '#F5F3FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    alignSelf: 'center',
  },
  furnitureEmoji: {
    fontSize: 28,
  },
  furnitureName: {
    color: '#4C1D95',
    fontWeight: '600',
    fontSize: 14,
    marginBottom: 6,
    textAlign: 'center',
    width: '100%',
  },
  furniturePrice: {
    color: '#7C3AED',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 4,
    textAlign: 'center',
    width: '100%',
  },
  furnitureSizeLabel: {
    color: '#A78BFA',
    fontSize: 11,
    textAlign: 'center',
    width: '100%',
  },
  placedList: {
    marginTop: 24,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148, 163, 184, 0.1)',
  },
  sectionTitle: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 14,
    paddingHorizontal: 4,
  },
  placedScroll: {
    gap: 12,
    paddingRight: 4,
  },
  placedItemCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 16,
    backgroundColor: '#1e293b',
    borderWidth: 1,
    borderColor: 'transparent',
    gap: 14,
    minWidth: 200,
  },
  placedItemCardActive: {
    borderColor: '#2563eb',
  },
  placedItemEmoji: {
    fontSize: 24,
  },
  placedItemMeta: {
    flex: 1,
  },
  placedItemName: {
    color: '#f8fafc',
    fontWeight: '600',
    fontSize: 14,
  },
  placedItemPrice: {
    color: '#38bdf8',
    fontSize: 12,
    marginTop: 2,
  },
  removeButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#0f172a',
    borderRadius: 10,
  },
  removeButtonText: {
    color: '#f1f5f9',
    fontSize: 12,
  },
  transformToolbar: {
    marginTop: 24,
    backgroundColor: '#111827',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#1e293b',
  },
  toolbarTitle: {
    color: '#f8fafc',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 14,
    textAlign: 'center',
  },
  controlRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 10,
  },
  controlButton: {
    flex: 1,
    backgroundColor: '#1e293b',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
  },
  controlButtonText: {
    color: '#e2e8f0',
    fontWeight: '600',
    fontSize: 13,
  },
  deleteButton: {
    backgroundColor: '#7f1d1d',
  },
  deleteButtonText: {
    color: '#fecaca',
  },
  clearAllButton: {
    backgroundColor: '#1f2937',
  },
  clearAllButtonText: {
    color: '#facc15',
  },
  errorBanner: {
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
    borderLeftWidth: 4,
    borderLeftColor: '#DC2626',
    padding: 12,
    marginHorizontal: 12,
    marginTop: 8,
    borderRadius: 8,
    maxWidth: '80%',
  },
  errorBannerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  errorText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  loadingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginHorizontal: 12,
    marginTop: 8,
    gap: 8,
  },
  loadingTextPrimary: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  placingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 8,
  },
  placingText: {
    color: '#4C1D95',
    fontSize: 14,
    fontWeight: '600',
  },
  interactiveControls: {
    flexDirection: 'row',
    gap: 8,
    marginLeft: 8,
  },
  helpButton: {
    backgroundColor: 'rgba(59, 130, 246, 0.8)',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  helpButtonText: {
    fontSize: 20,
  },
  tutorialButton: {
    backgroundColor: 'rgba(139, 92, 246, 0.8)',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tutorialButtonText: {
    fontSize: 20,
  },
  interactiveStatsPanel: {
    position: 'absolute',
    top: 360,
    right: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 20,
    padding: 18,
    minWidth: 200,
    maxWidth: 200,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.5)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 12,
    zIndex: 13,
  },
  interactiveStatsTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  interactiveStatsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  interactiveStatItem: {
    flex: 1,
    minWidth: 80,
    backgroundColor: 'rgba(30, 41, 59, 0.6)',
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.2)',
  },
  interactiveStatIcon: {
    fontSize: 24,
    marginBottom: 4,
  },
  interactiveStatValue: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 2,
  },
  interactiveStatLabel: {
    color: '#94a3b8',
    fontSize: 10,
    fontWeight: '500',
  },
  roomUtilization: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(148, 163, 184, 0.2)',
  },
  utilizationLabel: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  utilizationBar: {
    height: 8,
    backgroundColor: 'rgba(30, 41, 59, 0.6)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  utilizationFill: {
    height: '100%',
    backgroundColor: '#3b82f6',
    borderRadius: 4,
  },
  tutorialOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  tutorialModal: {
    backgroundColor: '#1e293b',
    borderRadius: 20,
    padding: 24,
    width: '85%',
    maxWidth: 400,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.5)',
  },
  tutorialHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  tutorialTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
    flex: 1,
  },
  tutorialCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tutorialCloseText: {
    color: '#ef4444',
    fontSize: 18,
    fontWeight: '700',
  },
  tutorialDescription: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 20,
  },
  tutorialProgress: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 20,
  },
  tutorialDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(148, 163, 184, 0.3)',
  },
  tutorialDotActive: {
    backgroundColor: '#3b82f6',
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  tutorialDotCompleted: {
    backgroundColor: '#22c55e',
  },
  tutorialButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  tutorialNavButton: {
    flex: 1,
    backgroundColor: 'rgba(30, 41, 59, 0.6)',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  tutorialNavButtonPrimary: {
    backgroundColor: '#3b82f6',
    borderColor: '#3b82f6',
  },
  tutorialNavText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
  },
  helpPanel: {
    position: 'absolute',
    bottom: 200,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.98)',
    borderRadius: 24,
    padding: 20,
    maxHeight: 400,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.6)',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 16,
  },
  helpPanelHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  helpPanelTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  helpPanelClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  helpPanelCloseText: {
    color: '#ef4444',
    fontSize: 16,
    fontWeight: '700',
  },
  helpPanelContent: {
    maxHeight: 320,
  },
  helpItem: {
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(148, 163, 184, 0.2)',
  },
  helpItemTitle: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 6,
  },
  helpItemText: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 18,
  },
  measurementControls: {
    position: 'absolute',
    top: 180,
    right: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 20,
    padding: 16,
    minWidth: 200,
    maxWidth: 200,
    borderWidth: 2,
    borderColor: '#34C759',
    shadowColor: '#34C759',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 12,
    zIndex: 14,
  },
  measurementControlsTitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  measurementButtons: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
  },
  measurementButton: {
    flex: 1,
    minWidth: 60,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  measurementButtonActive: {
    backgroundColor: '#34C759',
    borderColor: '#30D158',
    shadowColor: '#34C759',
    shadowOpacity: 0.4,
  },
  measurementButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  measurementHint: {
    color: '#94A3B8',
    fontSize: 11,
    textAlign: 'center',
    marginTop: 4,
  },
  measurementResults: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: '#34C759',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  measurementResultsTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 12,
    textAlign: 'center',
  },
  measurementResultItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  measurementResultLabel: {
    color: '#94A3B8',
    fontSize: 14,
    fontWeight: '600',
  },
  measurementResultValue: {
    color: '#34C759',
    fontSize: 16,
    fontWeight: '700',
  },
  clearMeasurementButton: {
    marginTop: 12,
    backgroundColor: 'rgba(255, 59, 48, 0.2)',
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF3B30',
  },
  clearMeasurementButtonText: {
    color: '#FF3B30',
    fontSize: 14,
    fontWeight: '600',
  },
  demoButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(52, 199, 89, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  demoButtonActive: {
    backgroundColor: 'rgba(255, 59, 48, 0.8)',
  },
  demoButtonText: {
    fontSize: 20,
  },
  demoModeIndicator: {
    position: 'absolute',
    top: 120,
    left: 20,
    backgroundColor: 'rgba(52, 199, 89, 0.95)',
    borderRadius: 16,
    padding: 16,
    minWidth: 250,
    borderWidth: 2,
    borderColor: '#34C759',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  demoModeIcon: {
    fontSize: 32,
  },
  demoModeContent: {
    flex: 1,
  },
  demoModeTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
  },
  demoModeStep: {
    color: '#DCFCE7',
    fontSize: 13,
    marginBottom: 8,
  },
  stopDemoButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignSelf: 'flex-start',
  },
  stopDemoButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  rotationIndicator: {
    color: '#5AC8FA',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
    marginBottom: 8,
  },
  persistenceControls: {
    position: 'absolute',
    top: 100,
    right: 20,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    zIndex: 15,
    maxWidth: 200,
  },
  persistenceButton: {
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(59, 130, 246, 0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  persistenceButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  multiSelectControls: {
    position: 'absolute',
    top: 100,
    left: 20,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    alignItems: 'center',
    zIndex: 15,
  },
  multiSelectButton: {
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  multiSelectButtonActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    borderColor: '#3b82f6',
  },
  multiSelectButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  multiSelectActionButton: {
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  multiSelectGroupButton: {
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    borderColor: 'rgba(139, 92, 246, 0.6)',
  },
  multiSelectActionTextDisabled: {
    opacity: 0.5,
  },
  multiSelectDeleteButton: {
    backgroundColor: 'rgba(239, 68, 68, 0.2)',
    borderColor: '#ef4444',
  },
  multiSelectActionText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '600',
  },
  groupControls: {
    position: 'absolute',
    top: 160,
    left: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    borderRadius: 20,
    padding: 14,
    minWidth: 180,
    borderWidth: 2,
    borderColor: 'rgba(139, 92, 246, 0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 12,
    zIndex: 14,
  },
  groupControlsTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  groupActionButton: {
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.6)',
  },
  groupActionText: {
    color: '#a78bfa',
    fontSize: 13,
    fontWeight: '600',
  },
  magneticSnapIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(139, 92, 246, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.5)',
  },
  magneticSnapIcon: {
    fontSize: 16,
  },
  magneticSnapText: {
    color: '#a78bfa',
    fontSize: 12,
    fontWeight: '600',
  },
  dimensionLabel: {
    marginTop: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  dimensionLabelText: {
    color: '#5ac8fa',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  previewModeControls: {
    position: 'absolute',
    bottom: 100,
    left: 20,
    right: 20,
    alignItems: 'center',
  },
  previewModeButton: {
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.5)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewModeButtonActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    borderColor: '#3b82f6',
  },
  previewModeButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  errorActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
    width: '100%',
  },
  retryButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  retryButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  fallbackBanner: {
    backgroundColor: 'rgba(251, 191, 36, 0.9)',
    borderLeftWidth: 4,
    borderLeftColor: '#fbbf24',
    padding: 12,
    marginHorizontal: 20,
    marginTop: 10,
    borderRadius: 8,
    position: 'relative',
  },
  fallbackDismissButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
  },
  fallbackDismissText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  fallbackText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
    paddingRight: 30,
  },
  fallbackButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  fallbackContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  fallbackButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '600',
  },
  accessibilityControls: {
    position: 'absolute',
    bottom: 250,
    left: 20,
    flexDirection: 'row',
    gap: 8,
    zIndex: 12,
  },
  accessibilityButton: {
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  accessibilityButtonActive: {
    backgroundColor: 'rgba(139, 92, 246, 0.3)',
    borderColor: '#8b5cf6',
  },
  accessibilityButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#1e293b',
    borderRadius: 16,
    padding: 24,
    width: '85%',
    maxWidth: 400,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  modalSubtitle: {
    color: '#94a3b8',
    fontSize: 14,
    marginBottom: 16,
  },
  modalInput: {
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
    borderRadius: 8,
    padding: 12,
    color: '#FFFFFF',
    fontSize: 16,
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-end',
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    minWidth: 80,
    alignItems: 'center',
  },
  modalButtonCancel: {
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  modalButtonSave: {
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    borderWidth: 1,
    borderColor: '#3b82f6',
  },
  modalButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  modalButtonSaveText: {
    color: '#60a5fa',
  },
  // Bottom Sheet Modal Styles
  bottomSheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    zIndex: 100,
  },
  bottomSheetBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  bottomSheetContainer: {
    backgroundColor: '#F5F3FF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 8,
    paddingBottom: 20,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 20,
    width: '100%',
    overflow: 'hidden',
  },
  bottomSheetCloseButton: {
    position: 'absolute',
    right: 16,
    top: 12,
    padding: 4,
    zIndex: 10,
  },

  // New styles for enhanced features
  panelDragHandle: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: 'transparent',
  },
  dragHandleBar: {
    width: 40,
    height: 4,
    backgroundColor: 'rgba(124, 58, 237, 0.3)',
    borderRadius: 2,
  },
  panelTitleContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    paddingHorizontal: 16,
    minHeight: 20,
  },
  bottomPanelHidden: {
    transform: [{ translateY: 300 }],
  },
  panelScrollContainer: {
    flex: 1,
    minHeight: 0, // Critical: Allows ScrollView to properly constrain and scroll
  },
  panelScrollContent: {
    paddingBottom: 20,
    flexGrow: 1,
  },
  categoryFilter: {
    maxHeight: 50,
    marginBottom: 8,
  },
  categoryFilterContent: {
    paddingHorizontal: 12,
    gap: 8,
  },
  categoryButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(124, 58, 237, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  categoryButtonActive: {
    backgroundColor: '#6B4CE6',
    borderColor: '#6B4CE6',
    shadowColor: '#6B4CE6',
    shadowOpacity: 0.2,
  },
  categoryButtonText: {
    color: '#7C3AED',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  categoryButtonTextActive: {
    color: '#FFFFFF',
  },
  furnitureThumbnail: {
    width: 60,
    height: 60,
    borderRadius: 8,
    backgroundColor: 'rgba(148, 163, 184, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  thumbnailOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 8,
  },
  furnitureCategoryLabel: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 4,
    textTransform: 'capitalize',
  },
  loadingContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingTextSecondary: {
    marginTop: 12,
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
  },
  errorContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  errorTextSecondary: {
    fontSize: 14,
    color: '#ef4444',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 4,
  },
  errorSubtext: {
    fontSize: 12,
    color: '#94a3b8',
    textAlign: 'center',
  },
  emptyContainer: {
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: '#94a3b8',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 4,
  },
  emptySubtext: {
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
  },
  totalCostContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
    borderTopWidth: 2,
    borderTopColor: 'rgba(34, 197, 94, 0.4)',
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(34, 197, 94, 0.3)',
    shadowColor: '#22c55e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  totalCostLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#22c55e',
    letterSpacing: 0.3,
  },
  totalCostValue: {
    fontSize: 22,
    fontWeight: '800',
    color: '#22c55e',
    letterSpacing: 0.5,
  },
  snapToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    borderRadius: 8,
    marginBottom: 8,
  },
  snapToggleLabel: {
    fontSize: 12,
    color: '#94a3b8',
    fontWeight: '600',
  },
  toggleSwitch: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.3)',
  },
  toggleSwitchActive: {
    backgroundColor: 'rgba(34, 197, 94, 0.3)',
    borderColor: '#22c55e',
  },
  toggleSwitchText: {
    fontSize: 11,
    color: '#94a3b8',
    fontWeight: '600',
  },
  safetyBannerDanger: {
    backgroundColor: 'rgba(239, 68, 68, 0.9)',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#ef4444',
    marginTop: 12,
  },
  safetyBannerWarning: {
    backgroundColor: 'rgba(251, 191, 36, 0.9)',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#fbbf24',
    marginTop: 12,
  },
  safetyBannerSafe: {
    backgroundColor: 'rgba(34, 197, 94, 0.2)',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(34, 197, 94, 0.5)',
    marginTop: 12,
  },
  safetyBannerTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  safetyBannerText: {
    fontSize: 14,
    color: '#FFFFFF',
    lineHeight: 20,
  },
  safetyBannerRecommendations: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.3)',
  },
  safetyBannerRecText: {
    fontSize: 12,
    color: '#FFFFFF',
    marginTop: 4,
    opacity: 0.9,
  },
});

export const errorBoundaryStyles = StyleSheet.create({
  errorContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#1a1f2e',
  },
  errorText: {
    fontSize: 16,
    color: '#ef4444',
    marginBottom: 16,
    textAlign: 'center',
  },
  tooltipContainer: {
    position: 'absolute',
    bottom: 200,
    right: 20,
    zIndex: 1000,
    maxWidth: 200,
    minWidth: 160,
  },
  tooltipContent: {
    backgroundColor: 'rgba(15, 23, 42, 0.95)',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 6,
  },
  tooltipHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  tooltipTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#ffffff',
    flex: 1,
  },
  tooltipCloseButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(148, 163, 184, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 6,
  },
  tooltipCloseText: {
    fontSize: 16,
    color: '#94a3b8',
    lineHeight: 18,
  },
  tooltipText: {
    fontSize: 11,
    color: '#94a3b8',
    marginBottom: 3,
  },
  tooltipPrice: {
    fontSize: 14,
    fontWeight: '600',
    color: '#22c55e',
    marginBottom: 4,
  },
  tooltipHint: {
    fontSize: 10,
    color: '#60a5fa',
    marginTop: 2,
    fontStyle: 'italic',
  },
  retryButton: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  customizationModal: {
    position: 'absolute',
    bottom: 200,
    left: 20,
    right: 20,
    zIndex: 1000,
  },
  customizationContent: {
    backgroundColor: 'rgba(15, 23, 42, 0.98)',
    padding: 20,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    maxHeight: 400,
  },
  customizationTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#ffffff',
    marginBottom: 16,
  },
  customizationSection: {
    marginBottom: 16,
  },
  customizationSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#94a3b8',
    marginBottom: 8,
  },
  colorOption: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 2,
    borderColor: '#ffffff',
  },
  materialOptions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  materialOption: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: 'rgba(59, 130, 246, 0.2)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.5)',
  },
  materialOptionText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '600',
  },
  sizeControls: {
    gap: 8,
  },
  sizeLabel: {
    fontSize: 12,
    color: '#94a3b8',
  },
  customizationCloseButton: {
    marginTop: 16,
    paddingVertical: 12,
    backgroundColor: '#3b82f6',
    borderRadius: 8,
    alignItems: 'center',
  },
  customizationCloseText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ffffff',
  },
  anchorIndicator: {
    position: 'absolute',
    top: 60,
    left: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(34, 197, 94, 0.9)',
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    zIndex: 100,
  },
  anchorIndicatorText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
  },
  anchorSaveButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 4,
  },
  anchorSaveButtonText: {
    fontSize: 10,
    fontWeight: '600',
    color: '#ffffff',
  },
  retryButtonSecondary: {
    backgroundColor: '#3b82f6',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  retryButtonTextSecondary: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  loadMoreContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 120,
  },
  loadMoreButton: {
    backgroundColor: colors.accent,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadMoreText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
});
